/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function crop(image: string, x: number, y: number, w: number, h: number, out: string): void
export declare function findImage(image: string, template: string): Point
export declare function matchTemplate(image: string, template: string): Point
export declare class Point {
  x: number
  y: number
  score: number
}
